MyShop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='index'),
    path('products/', mainapp_views.products, name='products'),
    path('context', mainapp_views.test_context)
]

cartapp/urls.py
from django.urls import path

import cartapp.views as cartapp

app_name = 'cartapp'

urlpatterns = [
    path('add/<int:id_product>/', cartapp.cart_add, name='cart_add'),
    path('clear/', cartapp.cart_clear, name='cart_clear'),
    path('edit/<int:id>/<int:quantity>/', cartapp.cart_edit, name='cart_edit'),
    path('clear_position/<int:id_product>/', cartapp.cart_clear_position, name='cart_clear_position')
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp import views as mainapp_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='main'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cartapp/models.py
from django.db import models

from authapp.models import User
from mainapp.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def sum(self):
        return self.quantity * self.product.price

    def __str__(self):
        return f'Корзина для {self.user.first_name}, продукт {self.product.name}'

cartapp/views.py
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse

from mainapp.models import Product
from cartapp.models import Cart


@login_required()
def cart_add(request, id_product=None):
    product = get_object_or_404(Product, id=id_product)
    carts = Cart.objects.filter(user=request.user, product=product)

    if not carts.exists():
        cart = Cart(user=request.user, product=product)
        cart.quantity += 1
        cart.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        cart = carts.first()
        cart.quantity += 1
        cart.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def cart_edit(request, id, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        cart = Cart.objects.get(id=int(id))
        if quantity > 0:
            cart.quantity = quantity
            cart.save()
        else:
            cart.delete()
        carts = Cart.objects.filter(user=request.user)
        context = {
            'carts': carts,
        }
        result = render_to_string('cartapp/cart.html', context)
        return JsonResponse({'result': result})


@login_required
def cart_clear_position(request, id_product=None):
    cart = Cart.objects.get(id=id_product)

    cart.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def cart_clear(request):
    cart = Cart.objects.all()
    cart.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))




# @login_required
# def cart_add_item(request, id_product=None):
#     cart = Cart.objects.get(id=id_product)
#     cart.quantity += 1
#     cart.save()
#     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
#
#
# @login_required
# def cart_remove_item(request, id_product=None):
#     cart = Cart.objects.get(id=id_product)
#
#     if cart.quantity > 1:
#         cart.quantity -= 1
#         cart.save()
#         return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
#
#     if cart.quantity == 1:
#         cart.delete()
#         return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
#
#
# @login_required
# def cart_clear_position(request, id_product=None):
#     cart = Cart.objects.get(id=id_product)
#
#     cart.delete()
#     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
#
#
# @login_required
# def cart_clear(request):
#     cart = Cart.objects.all()
#     cart.delete()
#     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

cartapp/templates/cartapp/cart.html
{#{% if carts %}#}
{#    <div class="cart_list">#}
{#    <div class="col-lg-5">#}
{#        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">#}
{#            Корзина <span class="badge badge-secondary badge-pill">{{ carts|length }}</span>#}
            {# Решил здесь оставить счёт по позициям, общее число ниже #}
{#        </h4>#}
{#        {% for cart in carts %}#}
{#            <div class="card mb-3">#}
{#                <div class="card-body">#}
{#                    <h5 class="card-title">{{ cart.product.name }}</h5>#}
{#                    <p class="card-text">{{ cart.product.short_desc }}</p>#}
{#                </div>#}
{#                <ul class="list-group list-group-flush">#}
{#                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">#}
{#                        <span class="text-muted">{{ cart.quantity }} шт.</span>#}
{#                        <span class="text-muted">{{ cart.product.price }}.</span>#}
{#                    </li>#}
{#                    <li class="list-group-item bg-light">#}
{#                        <div class="row text-center">#}
{#                            <div class="col-lg-4">#}
{#                                <div class="col-lg-4">#}
{#                                    <input name="{{ cart.id }}" type="number" class="form-control"#}
{#                                           value="{{ cart.quantity }}" min="0">#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="col-lg-4">{{ cart.sum }} руб.</div>#}
{#                            <div class="col-lg-4">#}
{#                                <a href="{% url 'cart:cart_clear_position' cart.id %}"#}
{#                                   data-el-type="clearPositionButton" data-id="{{ cart.id }}">#}
{#                                    <i class="fas fa-trash"></i>#}
{#                                </a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#        {% endfor %}#}
{#        <div class="card mb-3">#}
{#            <div class="card-footer">#}
{#                <p class="float-left">Итого: {{ carts.0.count_total_quantity }} товаров на сумму </p>#}
{#                <h4 class="float-right">{{ carts.0.count_total_price }} руб.</h4>#}
{#            </div>#}
{#        </div>#}
{#        <a href="{% url 'cart:cart_clear' %}" class="btn btn-danger btn-lg float-left" role="button"#}
{#           data-el-type="clearButton">Очистить#}
{#            корзину</a>#}
{#        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>#}
{#    </div>#}
{#{% else %}#}
{#    <h4 class="mt-3 mb-3 mb-3 text-center">#}
{#        Корзина пуста#}
{#    </h4>#}
{#{% endif %}#}
{#</div>#}



<div class="cart_list">
    {% if carts %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ carts.0.total_quantity }}</span>
        </h4>
        {% for cart in carts %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ cart.product.name }}</h5>
                    <p class="card-text">{{ cart.product.short_desc }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ cart.id }}" type="number" class="form-control"
                                       value="{{ cart.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ cart.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'cart:cart_clear_position' cart.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ carts.0.total_sum }} руб.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    {% else %}
        <h4 class="mt-3 mb-3 mb-3 text-center">
            Корзина пуста
        </h4>
    {% endif %}
</div>