MyShop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='index'),
    path('products/', mainapp_views.products, name='products'),
    path('context', mainapp_views.test_context)
]

authapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from authapp import views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.UserLoginView.as_view(), name='login'),
    path('logout', authapp_views.logout, name='logout'),
    path('register/', authapp_views.UserSignUpView.as_view(), name='register'),
    path('profile/', authapp_views.UserProfileView.as_view(), name='profile'),
    path('auth/', include('mainapp.urls', ))

]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp import views as mainapp_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='main'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    birthdate = models.DateField(auto_now=False, blank=True, null=True)

    def __str__(self):
        return self.username

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'

        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User

        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'

        self.fields['email'].widget.attrs['placeholder'] = 'Введите электронную почту'

        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите Ваше имя'

        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите Вашу фамилию'

        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'

        self.fields['password2'].widget.attrs['placeholder'] = 'Подтвердите пароль'

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'avatar', 'username', 'email', 'birthdate')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from django.contrib import auth, messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, UpdateView

from authapp.models import User
from cartapp.models import Cart


class UserLoginView(LoginView):
    authentication_form = UserLoginForm
    template_name = 'authapp/login.html'
    redirect_authenticated_user = True
    success_url = 'main'

    def get_context_data(self, **kwargs):
        context = super(UserLoginView, self).get_context_data(**kwargs);
        context.update({'title': 'авторизация'})
        context.update({'style_link': 'css/auth-admin.css'})
        context.update({'script_link': 'js/auth-admin.js'})
        return context

# Не вижу смысла ради двух строчек создавать класс, который съест больше памяти, чем функция
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


class UserSignUpView(CreateView):
    model = User
    template_name = 'authapp/register.html'
    success_url = reverse_lazy('authapp:login')
    form_class = UserRegisterForm

    def get_context_data(self, **kwargs):
        context = super(UserSignUpView, self).get_context_data(**kwargs)
        context.update({'title': 'регистрация'})
        context.update({'style_link': 'css/auth-admin.css'})
        context.update({'script_link': 'js/auth-admin.js'})
        return context


class UserProfileView(UpdateView):
    model = User
    template_name = 'authapp/profile.html'
    success_url = reverse_lazy('auth:profile')
    form_class = UserProfileForm

    def get_context_data(self, request, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context.update({'title': 'профиль'})
        context.update({'style_link': 'css/profile.css'})

        carts = Cart.objects.filter(user=request.user)
        context.update({'carts': carts})
        return context

# def profile(request):
#     if request.method == "POST":
#         form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('auth:profile'))
#
#     else:
#         form = UserProfileForm(instance=request.user)
#
#     carts = Cart.objects.filter(user=request.user)
#
#     context = {
#         'title': 'профиль',
#         'style_link': 'css/profile.css',
#
#         'carts': carts,
#
#         'form': form
#     }
#
#     return render(request, 'authapp/profile.html', context)

# def login(request):
#     if request.method == 'POST':
#         form = UserLoginForm(data=request.POST)
#
#         if form.is_valid():
#             username = request.POST['username']
#             password = request.POST['password']
#
#             user = auth.authenticate(username=username, password=password)
#             if user and user.is_active:
#                 auth.login(request, user)
#                 return HttpResponseRedirect(reverse('main'))
#
#     else:
#         form = UserLoginForm()
#
#     context = {
#         'title': 'авторизация',
#         'style_link': 'css/auth-admin.css',
#         'script_link': 'js/auth-admin.js',
#
#         'form': form
#     }
#
#     return render(request, 'authapp/login.html', context)


# def register(request):
#     if request.method == "POST":
#         reg_form = UserRegisterForm(data=request.POST)
#         if reg_form.is_valid():
#             reg_form.save()
#             messages.success(request, 'Вы успешно зарегистрировались')
#             return HttpResponseRedirect(reverse('authapp:login'))
#     else:
#         reg_form = UserRegisterForm()
#
#     context = {
#         'title': 'регистрация',
#         'style_link': 'css/auth-admin.css',
#         'script_link': 'js/auth-admin.js',
#
#         'form': reg_form
#     }
#
#     return render(request, 'authapp/register.html', context)

authapp/templates/authapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <title>GeekShop - {{ title|title }}</title>

    <link rel="icon" href="{% static 'img/pycharm-PyCharm_400x400_Twitter_logo_white.png' %}" sizes="16x16"
          type="image/png">


    <link href="{% static style_link %}" rel="stylesheet"/>
    <script src="{% static script_link %}" defer></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous" defer></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous" defer></script>

</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>

</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% load staticfiles %}

{% block title %}
    {{ title|title }}
{% endblock %}

{% block content %}
    <div class="col-lg-5">
        {% if messages or form.non_field_errors %}
            <div class="alert
            {% if messages %}alert-success{% else %} alert-warning{% endif %}
             alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                <strong>Holy guacamole!</strong>
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {% for error in form.non_field_errors%}
                        {{ error }}
                    {% endfor %}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'authapp:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                        {#                        <input class="form-control py-4" id="inputEmailAddress" type="email"#}
                        {#                               placeholder="Введите имя пользователя"/>#}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                        {#                        <input class="form-control py-4" id="inputPassword" type="password"#}
                        {#                               placeholder="Введите пароль"/>#}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a class="small" href="#">Забыли пароль?</a>
                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'authapp:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
            </div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block style %}
    <link href="{% static style_link %}" rel="stylesheet">
{% endblock %}

{% block title %}
    {{ title|title }}
{% endblock %}

{% block script %}
    <script src="{% static 'js/cart.js' %}" defer></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="



                                 {% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'vendor/img/users/default_avatar.jpg' %}{% endif %}"
                         class="img-thumbnail"
                         alt="pic">
                </div>
                <form action="{% url 'authapp:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.avatar }}
                                <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.birthdate.id_for_label }}">День рождения</label>
                            {{ form.birthdate }}
                        </div>
                        <div class="col-lg-6" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4">
                {% include 'cartapp/cart.html' %}
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ title|title }}
{% endblock %}

{% block content %}
    <div class="col-lg-7">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                <strong>Holy guacamole!</strong>
                {% for error in form.errors %}
                    {{ error|escape }}
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'authapp:register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.if_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                {{ form.password1 }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                    пароля</label>
                                {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-4 mb-0">
                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'authapp:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
            </div>
        </div>
    </div>
{% endblock %}