MyShop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='index'),
    path('products/', mainapp_views.products, name='products'),
    path('context', mainapp_views.test_context)
]

authapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from authapp import views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.UserLoginView.as_view(), name='login'),
    path('logout', authapp_views.logout, name='logout'),
    path('register/', authapp_views.UserSignUpView.as_view(), name='register'),
    path('profile/', authapp_views.UserProfileView.as_view(), name='profile'),
    path('auth/', include('mainapp.urls', ))

]

cartapp/urls.py
from django.urls import path

import cartapp.views as cartapp

app_name = 'cartapp'

urlpatterns = [
    path('add/<int:id_product>/', cartapp.cart_add, name='cart_add'),
    path('clear/', cartapp.cart_clear, name='cart_clear'),
    path('edit/<int:id>/<int:quantity>/', cartapp.cart_edit, name='cart_edit'),
    path('clear_position/<int:id_product>/', cartapp.cart_clear_position, name='cart_clear_position')
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:category_id>/', mainapp.products, name='products'),
    path('page/<int:page>', mainapp.products, name='products_page')
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp import views as mainapp_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='main'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='product_img', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=256, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.name} {self.category.name}'

mainapp/views.py
from django.shortcuts import render
from django.utils import timezone
from mainapp.models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    context = {
        'title': 'geek shop',

        'style_link': 'css/index.css',

        'date': timezone.now()

    }

    return render(request, 'mainapp/index.html', context)


def products(request, page=1, category_id=None):
    context = {
        'title': 'geek shop - каталог',
        'currency': 'руб.',
        'style_link': 'css/products.css',
        'categories': ProductCategory.objects.all(),
        'products': Product.objects.all()
    }

    if category_id:
        filtered_products = Product.objects.filter(category_id=category_id)
        context.update({'products': filtered_products})

    paginator = Paginator(context['products'], 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context.update({'products': products_paginator})

    return render(request, 'mainapp/products.html', context)

mainapp/templates/mainapp/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>GeekShop - {% block title %}{% endblock %}</title>

    <link rel="icon" href="{% static 'img/pycharm-PyCharm_400x400_Twitter_logo_white.png' %}" sizes="16x16"
          type="image/png">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block style %}{% endblock %}

    {#      В нашем случае скрипты идентичны, но может возникнуть необходимость подключить к странице собственный #}
    {#      скрипт, так что заранее подготовлю блок на такой случай #}
    {% block script %}{% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}" defer></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}" defer></script>

    <!-- FontAwesome script -->
    <script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous" defer></script>

</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:products' %}">Каталог <i class="fas fa-shopping-bag"></i></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'authapp:profile' %}">{{ user.first_name|capfirst }} <i class="fas fa-user-circle"></i></a>
                </li>
                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin_staff:index' %}">
                        <i class="fas fa-users-cog"></i>
                    </a>
                </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:login' %}">Войти <i
                                class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block title %}
{{ title|title }}
{% endblock %}


{% block style %}
    <link href="{% static style_link %}" rel="stylesheet">
{% endblock %}


{% block script %}

{% endblock %}


{% block content %}
    <!-- Page Content -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.<br>
                    <br>Текущая дата: {{ date }}
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'mainapp:products' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load humanize %}
{% load l10n %}


{% block title %}
    {{ title|title }}
{% endblock %}


{% block style %}
    <link href="{% static style_link %}" rel="stylesheet">
{% endblock %}


{% block script %}

{% endblock %}


{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'mainapp:products' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in products %}

                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="/media/{{ product.image }}"
                                         alt="pic">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price|intcomma }} {{ currency }}</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'cart:cart_add' product.id %}">
                                        <button type="button" class="btn btn-outline-success">Отправить в корзину
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                </div>
                <!-- /.row -->
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %} {% url 'mainapp:products_page' products.previous_page_number %} {% else %} # {% endif %}">
                                Previous
                            </a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'mainapp:products_page' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_next %} {% url 'mainapp:products_page' products.next_page_number %} {% else %} # {% endif %}">
                                Next
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->



{% endblock %}


{% block footer %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}